'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {Browser}=require('../../tests/lib/cdp');
const {startServer}=require('../tools/serve');

test('map and Quest: actual geography, session pins, navigation, focus and unpaused world',{timeout:180000},async t=>{
  const server=await startServer(0);let browser,page;
  try{
    browser=await Browser.launch();page=await browser.newPage();
    await page.session.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
    await page.addInitScript(`window.__storageAccess=[];for(const method of ['getItem','setItem','removeItem','clear'])Storage.prototype[method]=function(){window.__storageAccess.push(method);throw new Error('Native storage access');};`);
    const url='http://127.0.0.1:'+server.address().port;
    await page.goto(url,{waitFor:()=>!!window.WorldDemo});
    assert.equal(await page.evaluate(()=>WorldDemo.ready),true);
    const click=selector=>page.evaluate(sel=>document.querySelector(sel).click(),selector);
    const textButton=text=>page.evaluate(text=>[...document.querySelectorAll('#panel button')].find(b=>b.textContent===text).click(),text);
    const key=async(code,key)=>{await page.session.send('Input.dispatchKeyEvent',{type:'keyDown',code,key});await page.session.send('Input.dispatchKeyEvent',{type:'keyUp',code,key});};
    const input=(id,value)=>page.evaluate(({id,value})=>{const node=document.getElementById(id);node.value=value;node.dispatchEvent(new Event('input',{bubbles:true}));},{id,value});
    const shot=async name=>{const r=await page.session.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/track-world-'+name+'.png',Buffer.from(r.data,'base64'));};
    const pointer=async(type,x,y)=>page.session.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mouseReleased'?0:1,clickCount:1});
    const mapClick=async(x,z)=>{
      const point=await page.evaluate(({x,z})=>{const area=document.getElementById('world-map-area'),r=area.getBoundingClientRect();
        const p=WorldMapCore.project({x,z},WorldDemo.snapshot().map.view,r.width,r.height);return {x:r.left+p.x,y:r.top+p.y};},{x,z});
      await pointer('mousePressed',point.x,point.y);await pointer('mouseReleased',point.x,point.y);
    };
    const frame=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    await click('#enter');await page.waitFor(()=>!document.getElementById('minimap').hidden);
    assert.ok(await page.evaluate(()=>{
      const mini=document.getElementById('minimap').getBoundingClientRect(),hud=document.getElementById('gameplay-popup').getBoundingClientRect();
      return mini.left<60&&mini.top<60&&hud.top>mini.bottom;
    }),'minimap and Quest occupy the upper-left stack');
    await shot('map-hud');
    await t.test('stationary camera orbit changes map heading without waiting for the avatar to turn',async()=>{
      const before=await page.evaluate(()=>WorldDemo.snapshot().map.player);
      await pointer('mousePressed',800,500);await pointer('mouseMoved',860,500);await pointer('mouseReleased',860,500);await frame();
      const after=await page.evaluate(()=>({world:WorldDemo.snapshot().world,map:WorldDemo.snapshot().map.player,heading:Number(document.getElementById('minimap-canvas').dataset.heading)}));
      assert.ok(after.world.yaw>before.yaw+.2);assert.equal(after.map.facing,before.facing,'only the view turns');
      assert.equal(after.map.yaw,after.world.yaw);assert.equal(after.heading,after.world.yaw);
      await key('Home','Home');await frame();
    });
    await key('KeyM','m');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().panel),'map');
    await page.waitFor(()=>document.querySelectorAll('.map-marker').length===9);
    const bridge=await page.evaluate(()=>WorldDemo.snapshot().map.landmarks.find(p=>p.id==='bridge'));
    assert.deepEqual({id:bridge.id,name:bridge.name,icon:bridge.icon,x:bridge.x,z:bridge.z},{id:'bridge',name:'Little bridge',icon:'bridge',x:9.5,z:5});
    assert.ok(Math.abs(bridge.y-.425)<.001,'the bridge destination uses the deck height: '+JSON.stringify(bridge));
    assert.ok(await page.evaluate(()=>{
      const player=document.querySelector('.map-player'),marker=document.querySelector('.map-marker');
      return Number(getComputedStyle(player).zIndex)>Number(getComputedStyle(marker).zIndex||0)||getComputedStyle(marker).zIndex==='auto';
    }),'player remains visible above landmarks at the same coordinate');
    await shot('world-map');
    await t.test('clicked pin preview follows coordinates through pan/zoom, repositions and cancels without saving',async()=>{
      await mapClick(22,0);
      assert.equal(await page.evaluate(()=>!!document.getElementById('map-pin-preview')),true);
      const draft=await page.evaluate(()=>WorldDemo.snapshot().map.draft);
      assert.ok(Math.abs(draft.x-22)<.2&&Math.abs(draft.z)<.2);assert.ok(Number.isFinite(draft.y));
      await input('pin-name','A temporary spot');
      await page.evaluate(()=>document.getElementById('world-map-area').focus());await key('ArrowLeft','ArrowLeft');await click('#map-zoom-in');
      assert.ok(await page.evaluate(()=>{
        const s=WorldDemo.snapshot().map,area=document.getElementById('world-map-area'),preview=document.getElementById('map-pin-preview');
        const {width,height}=area.getBoundingClientRect(),expected=WorldMapCore.project(s.draft,s.view,width,height);
        return Math.abs(parseFloat(preview.style.left)-expected.x)<.1&&Math.abs(parseFloat(preview.style.top)-expected.y)<.1;
      }),'preview remains anchored to its world coordinate');
      await mapClick(20,1);
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.draft.name),'A temporary spot');
      assert.ok(await page.evaluate(()=>Math.abs(WorldDemo.snapshot().map.draft.x-20)<.2));
      await shot('pin-preview');await textButton('Cancel');
      assert.equal(await page.evaluate(()=>!!document.getElementById('map-pin-preview')),false);
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins.length),0);
      await textButton('Fit garden');await mapClick(48,7);
      assert.equal(await page.evaluate(()=>document.querySelector('.map-details .primary').disabled),true,'a point without a surface is not given a fake height');
      await mapClick(20,0);assert.equal(await page.evaluate(()=>document.querySelector('.map-details .primary').disabled),false);
      await textButton('Cancel');await textButton('Fit garden');
    });
    const before=await page.evaluate(()=>WorldDemo.snapshot());
    await page.evaluate(()=>document.getElementById('world-map-area').focus());
    await key('ArrowRight','ArrowRight');await key('Equal','+');
    let after=await page.evaluate(()=>WorldDemo.snapshot());
    assert.ok(after.map.view.x>before.map.view.x&&after.map.view.zoom>before.map.view.zoom);
    assert.ok(Math.hypot(after.world.position[0]-before.world.position[0],after.world.position[2]-before.world.position[2])<.1);
    const r=await page.evaluate(()=>{const r=document.getElementById('world-map-area').getBoundingClientRect();return {x:r.x+140,y:r.y+r.height/2};});
    const dragStart=after.map.view.x;
    await pointer('mousePressed',r.x,r.y);await pointer('mouseMoved',r.x+60,r.y+20);await pointer('mouseReleased',r.x+60,r.y+20);
    after=await page.evaluate(()=>WorldDemo.snapshot());assert.ok(after.map.view.x<dragStart);assert.equal(after.map.pins.length,0,'drag does not place a pin');
    await click('#map-recenter');
    assert.ok(await page.evaluate(()=>{const s=WorldDemo.snapshot().map;return Math.abs(s.view.x-s.player.x)<.1&&Math.abs(s.view.z-s.player.z)<.1;}));
    await textButton('Pin at map center');await textButton('Save pin');
    assert.equal(await page.evaluate(()=>!!document.getElementById('map-pin-preview')),true,'an unconfirmed pin has a temporary map symbol');
    assert.match(await page.evaluate(()=>document.getElementById('pin-status').textContent),/name/);
    await input('pin-name','ไทย <b>Quiet water</b>');
    await page.evaluate(()=>{const s=document.getElementById('pin-icon');s.value='leaf';s.dispatchEvent(new Event('change',{bubbles:true}));});
    await click('.toolbelt [data-panel="notebook"]');await click('[data-note-id]');await input('note-draft','Draft survives the map');
    await click('.toolbelt [data-panel="map"]');
    assert.equal(await page.evaluate(()=>document.getElementById('pin-name').value),'ไทย <b>Quiet water</b>','pin draft survives switching');
    await textButton('Save pin');
    assert.equal(await page.evaluate(()=>document.querySelectorAll('.map-details b').length),0,'pin labels remain text');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins.length),1);
    await click('#map-navigate');
    const originalPin=await page.evaluate(()=>WorldDemo.snapshot().map.pins[0]);
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target.id),originalPin.id);
    await t.test('selecting another place abandons the pin draft without changing saved pins or navigation',async()=>{
      const selectMarker=async id=>{
        const p=await page.evaluate(id=>{const r=document.querySelector('[data-map-place="'+id+'"]').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};},id);
        await pointer('mousePressed',p.x,p.y);await pointer('mouseReleased',p.x,p.y);
      };
      await textButton('Pin at map center');await input('pin-name','Abandon this new pin');
      await selectMarker(originalPin.id);
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.draft),null,'a saved marker replaces the unconfirmed pin editor');
      assert.equal(await page.evaluate(()=>!!document.getElementById('map-pin-preview')),false);
      assert.equal(await page.evaluate(()=>document.querySelector('.map-details h2').textContent),originalPin.name);
      assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('.map-details h2')),true);
      await textButton('Edit pin');await input('pin-name','Abandon this edit');
      await selectMarker('plaza');
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.draft),null);
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.selected),'plaza');
      assert.deepEqual(await page.evaluate(()=>WorldDemo.snapshot().map.pins),[originalPin]);
      assert.deepEqual(await page.evaluate(()=>WorldDemo.snapshot().map.target),originalPin,'selection does not change active navigation');
      await selectMarker(originalPin.id);
    });
    await textButton('Edit pin');await input('pin-name','Unkept name');await textButton('Cancel');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins[0].name),originalPin.name,'cancel retains saved pin');
    await textButton('Edit pin');await input('pin-name','Quiet water');await textButton('Save pin');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target.name),'Quiet water','active destination follows pin edit');
    await shot('map-pin');
    await textButton('Pin at map center');await input('pin-name','Replaced by Quest location');
    await click('.toolbelt [data-panel="quest"]');
    await click('[data-quest-node="task-pack"] button');
    assert.match(await page.evaluate(()=>document.querySelector('.quest-details').innerText),/No destination mapped/);
    assert.equal(await page.evaluate(()=>!!document.getElementById('quest-navigate')),false);
    await click('[data-quest-node="task-ripple"] button');await textButton('Show on map');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.selected),'bridge');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.draft),null,'Show on map opens the requested place instead of a stale draft');
    assert.equal(await page.evaluate(()=>document.querySelector('.map-details h2').textContent),'Little bridge');
    await click('.toolbelt [data-panel="quest"]');await click('#quest-navigate');
    await page.waitFor(()=>!document.getElementById('gameplay-popup').hidden);
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target.id),'bridge');
    assert.match(await page.evaluate(()=>document.getElementById('destination-name').textContent),/Draw a widening ripple/);
    const distanceBefore=await page.evaluate(()=>document.getElementById('destination-distance').textContent);
    await page.session.send('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyW',key:'w'});
    await page.waitFor(value=>document.getElementById('destination-distance').textContent!==value,{args:[distanceBefore],timeout:20000});
    await page.session.send('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyW',key:'w'});
    await click('#minimap');
    await page.evaluate(()=>{const select=document.getElementById('map-location');select.value='pin-1';select.dispatchEvent(new Event('change',{bubbles:true}));});
    await click('#map-navigate');await textButton('Remove pin');await textButton('Keep pin');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins.length),1);
    await textButton('Remove pin');await textButton('Confirm remove');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins.length),0);
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target),null,'removing a tracked pin clears its locator');
    await click('.toolbelt [data-panel="notebook"]');
    await click('[data-note-id]');
    assert.equal(await page.evaluate(()=>document.getElementById('note-draft').value),'Draft survives the map');
    await click('.toolbelt [data-panel="weather"]');
    await page.evaluate(()=>{const node=document.getElementById('weather-choice');node.value='rain';node.dispatchEvent(new Event('change',{bubbles:true}));});
    await click('.toolbelt [data-panel="map"]');
    const elapsed=await page.evaluate(()=>WorldDemo.snapshot().world.environment.elapsed);
    await page.waitFor(n=>WorldDemo.snapshot().world.environment.elapsed>n+1,{args:[elapsed]});
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().world.paused),false);
    for(const [width,height] of [[800,650],[390,740],[1100,560]]){
      await page.session.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
      await page.waitFor(()=>document.getElementById('world-map-area').clientWidth>0);
      assert.ok(await page.evaluate(()=>{
        const area=document.getElementById('world-map-area').getBoundingClientRect(),content=document.getElementById('panel-content').getBoundingClientRect(),bar=document.querySelector('.toolbelt').getBoundingClientRect();
        return document.documentElement.scrollWidth<=innerWidth&&area.height>=150&&content.bottom<=bar.top&&bar.right<=innerWidth;
      }),'map and companions fit '+width+'×'+height);
      await shot('map-'+width);
    }
    await click('#close-panel');await page.evaluate(()=>document.getElementById('world').focus());await key('KeyK','k');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().panel),'memory','Mind maps retain a direct shortcut');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().fixtureUnchanged),true);
    assert.deepEqual(await page.evaluate(()=>window.__storageAccess),[]);
    await t.test('a height-aware destination stays visible through the clock and follows the exact projected point',async()=>{
      await page.session.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
      await click('.toolbelt [data-panel="help"]');await textButton('Return to the start');
      await page.waitFor(()=>WorldDemo.snapshot().world.grounded);
      await click('.toolbelt [data-panel="map"]');await textButton('Fit garden');
      for(let i=0;i<5;i++)await click('#map-zoom-in');
      await mapClick(0,9);await input('pin-name','Behind the clock');await textButton('Save pin');
      const pin=await page.evaluate(()=>WorldDemo.snapshot().map.pins[0]);
      assert.ok(Math.abs(pin.y-.17)<.01,'pin is on the plaza surface');
      await click('#map-navigate');await click('#close-panel');
      await page.waitFor(()=>!document.getElementById('world-destination').hidden);
      const marker=await page.evaluate(()=>{const node=document.getElementById('world-destination'),r=node.getBoundingClientRect();
        return {world:WorldDemo.snapshot().world.destination,x:r.left+r.width/2,y:r.bottom,events:getComputedStyle(node).pointerEvents};});
      assert.equal(marker.world.occluded,true,'real scene geometry blocks the ray to the destination');
      assert.ok(Math.abs(marker.x-marker.world.projection.x)<.1&&Math.abs(marker.y-marker.world.projection.y)<.1,'marker tip is anchored to the actual world point');
      assert.equal(marker.events,'none','marker never intercepts camera dragging');await shot('destination-through-clock');
      await page.evaluate(()=>document.getElementById('world').focus());
      await pointer('mousePressed',800,500);await pointer('mouseMoved',860,470);await pointer('mouseReleased',860,470);await frame();
      assert.ok(await page.evaluate(()=>{const s=WorldDemo.snapshot().world.destination,r=document.getElementById('world-destination').getBoundingClientRect();
        return s.projection.inView&&Math.abs(r.bottom-s.projection.y)<.1&&Math.abs(r.left+r.width/2-s.projection.x)<.1;}),'turn and tilt update the world marker each frame');
      await pointer('mousePressed',600,400);await pointer('mouseMoved',1228,400);await pointer('mouseReleased',1228,400);await frame();
      assert.equal(await page.evaluate(()=>document.getElementById('world-destination').hidden),true,'a point behind the camera does not mirror onto the view');
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target.id),pin.id,'off-screen navigation stays active');
      await key('Home','Home');await click('.toolbelt [data-panel="map"]');
      await page.evaluate(()=>{const s=document.getElementById('map-location');s.value='terrace';s.dispatchEvent(new Event('change',{bubbles:true}));});
      await click('#map-navigate');
      assert.ok(await page.evaluate(()=>Math.abs(WorldDemo.snapshot().world.destination.y-.8)<.001),'landmark navigation uses the terrace height');
      await click('#map-stop');
      assert.equal(await page.evaluate(()=>WorldDemo.snapshot().world.destination),null);
      await page.evaluate(id=>{const s=document.getElementById('map-location');s.value=id;s.dispatchEvent(new Event('change',{bubbles:true}));},pin.id);
      await textButton('Remove pin');await textButton('Confirm remove');
    });
    if(await page.evaluate(()=>WorldDemo.snapshot().panel!=='map'))await click('.toolbelt [data-panel="map"]');
    await textButton('Pin at map center');await input('pin-name','Session ends');await textButton('Save pin');
    await page.goto(url,{waitFor:()=>!!window.WorldDemo});
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.pins.length),0,'reload starts a fresh pin session');
    assert.equal(await page.evaluate(()=>WorldDemo.snapshot().map.target),null);
    assert.deepEqual(page.errors,[]);
  }finally{
    if(page?.errors.length)t.diagnostic(JSON.stringify(page.errors));
    if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));
  }
});
